/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconClarityResistorLine: typeof import('~icons/clarity/resistor-line')['default']
  const IconFluentDeveloperBoard16Regular: typeof import('~icons/fluent/developer-board16-regular')['default']
  const IconIconParkOutlineFileQuestion: typeof import('~icons/icon-park-outline/file-question')['default']
  const IconIconParkOutlineResistor: typeof import('~icons/icon-park-outline/resistor')['default']
  const IconIconoirElectronicsTransistor: typeof import('~icons/iconoir/electronics-transistor')['default']
  const IconMdiGithub: typeof import('~icons/mdi/github')['default']
  const IconSystemUiconsCross: typeof import('~icons/system-uicons/cross')['default']
}
